name: Philips Academy

on:
  push:
    branches: [ "main", "yorick_dev" ]
  pull_request:
    branches: [ "main", "yorick_dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up devcontainer
      uses: devcontainers/ci@v0.3
      with:
        devcontainer-path: .devcontainer  
        
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
