name: Philips Academy

on:
  push:
    branches: [ "main", "yorick_dev" ]
  pull_request:
    branches: [ "main", "yorick_dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up devcontainer
      uses: devcontainers/ci@v0.3
      with:
        devcontainer-path: .devcontainer  

    - name: Create build directory
      run: |
        mkdir -p build
        cd build
        
    - name: Build the project
      run: |
         cmake ..
         cmake --build . 
